#!/usr/bin/env bash

case "$(uname -s)" in

   Darwin)
     echo 'Mac OS X'
     source /usr/local/etc/bash_completion.d/git-completion.bash
     ;;

   Linux)
     echo 'Linux'
     export LANG=en_US.UTF-8  # required by ROS2
     # Enable tab completion for `g` by marking it as an alias for `git`
     if type _git &> /dev/null && [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
       complete -o default -o nospace -F _git g;
     fi
     ;;
   CYGWIN*|MINGW32*|MSYS*)
     echo 'MS Windows'
     ;;

   # Add here more strings to compare
   # See correspondence table at the bottom of this answer

   *)
     echo 'other OS'
     ;;
esac

export PATH=${PATH}:${HOME}/Tools/scripts
export PATH=${PATH}:${HOME}/Tools/bin
#export LIBGL_ALWAYS_SOFTWARE=1

alias tree='tree --charset ASCII'
alias rsync='rsync -rRvul --no-implied-dirs --times'
alias grep='grep --color --exclude-dir=".svn" --exclude-dir=".git"'

source ${HOME}/Tools/dot_files/bash/themes/colors.theme.bash
source ${HOME}/Tools/dot_files/bash/aliases/available/general.aliases.bash

# Add tab completion for many Bash commands
if which brew > /dev/null && [ -f "$(brew --prefix)/share/bash-completion/bash_completion" ]; then
    source "$(brew --prefix)/share/bash-completion/bash_completion";
elif [ -f /etc/bash_completion ]; then
    source /etc/bash_completion
fi


source ${HOME}/Tools/dot_files/bash/completion/available/brew.completion.bash
source ${HOME}/Tools/dot_files/bash/completion/available/defaults.completion.bash
source ${HOME}/Tools/dot_files/bash/completion/available/dirs.completion.bash

# Git branch in prompt.
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\u@\h \W\[\033[32m\]\$(parse_git_branch)\[\033[00m\] $ "

